/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_201602598;

/**
 *
 * @author Hector
 */
public class Crear_Bibliografia extends javax.swing.JFrame {

    /**
     * Creates new form Crear_Bibliografia
     */
    public Crear_Bibliografia() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmasiva = new javax.swing.JButton();
        btnindividual = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmasiva.setText("Carga Masiva");
        btnmasiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmasivaActionPerformed(evt);
            }
        });
        getContentPane().add(btnmasiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        btnindividual.setText("Carga Individual");
        btnindividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnindividualActionPerformed(evt);
            }
        });
        getContentPane().add(btnindividual, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        btnvolver.setText("Volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1_201602598/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        // TODO add your handling code here:
        Usuario_Administrador ua=new Usuario_Administrador();
        ua.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnvolverActionPerformed

    private void btnindividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnindividualActionPerformed
        // TODO add your handling code here:
        Carga_Individual ci=new Carga_Individual();
        ci.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnindividualActionPerformed

    private void btnmasivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmasivaActionPerformed
        // TODO add your handling code here:
        Carga_Masiva cm=new Carga_Masiva();
        cm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnmasivaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crear_Bibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crear_Bibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crear_Bibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crear_Bibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crear_Bibliografia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnindividual;
    private javax.swing.JButton btnmasiva;
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel lblfondo;
    // End of variables declaration//GEN-END:variables
}
