/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_201602598;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 *
 * @author Hector
 */
public class Login extends javax.swing.JFrame {
    
PantallaPrincipal pal=new PantallaPrincipal();
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsalir = new javax.swing.JButton();
        lblusuario = new javax.swing.JLabel();
        lblpass = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        btncancelar = new javax.swing.JButton();
        lblimguser = new javax.swing.JLabel();
        btningresar = new javax.swing.JButton();
        txtpassw = new javax.swing.JPasswordField();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsalir.setText("Volver");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        lblusuario.setText("Usuario");
        getContentPane().add(lblusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        lblpass.setText("Contraseña");
        getContentPane().add(lblpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        txtusuario.setColumns(12);
        getContentPane().add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        lblimguser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1_201602598/Imagenes/loginuser.png"))); // NOI18N
        getContentPane().add(lblimguser, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        btningresar.setText("Ingresar");
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });
        getContentPane().add(btningresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        txtpassw.setColumns(12);
        getContentPane().add(txtpassw, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1_201602598/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        pal.setVisible(true);
        
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        
        txtpassw.setText("");
        txtusuario.setText("");
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed
        // TODO add your handling code here:
        //3-5
        char[] arrayc=txtpassw.getPassword();
        String pass=new String(arrayc);
        String a=txtusuario.getText();
       
            
      
        if((txtusuario.getText().equals("admin") && pass.equals("admin"))){
            Usuario_Administrador ua=new Usuario_Administrador();
            ua.setVisible(true);
            this.setVisible(false);
        }else{
            //JOptionPane.showMessageDialog(null, "Error");
            
            for(int i=0;i<Proyecto1_201602598.longi;i++){
                
                String u=new String(Proyecto1_201602598.usuario[i]);
                String[] coordenada=u.split(",");
                    
                    if((coordenada[0].equals(a))&&(coordenada[5].equals(pass))){
                        JOptionPane.showMessageDialog(null, "Bienvenido "+a);
                        Usuario_Normal un=new Usuario_Normal();
                        un.setVisible(true);
                        this.setVisible(false);
                        
                    }else if((coordenada[0].equals(a))&&!(coordenada[5].equals(pass))){
                        JOptionPane.showMessageDialog(null, "La contraseña es erronea","Error",WARNING_MESSAGE);
                        
                    }else if(!(coordenada[0].equals(a))&&(coordenada[5].equals(pass))){
                        JOptionPane.showMessageDialog(null, "El usuario es incorrecto","Error",WARNING_MESSAGE);
                    }else{
                        JOptionPane.showMessageDialog(null, "No existe este usuario, si desea crear uno "
                                + "nuevo debe ir al 5to nivel de la Biblioteca Central","Error "
                                ,WARNING_MESSAGE);
                    }
                
                
            }
       
    }//GEN-LAST:event_btningresarActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btningresar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblimguser;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JPasswordField txtpassw;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
