/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_201602598;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 *
 * @author Hector
 */
public class Modificar_Bibliografia extends javax.swing.JFrame {
int k;
int valor;
//Bibliografia b=new Bibliografia();
    /**
     * Creates new form Modificar_Bibliografia
     */
    public Modificar_Bibliografia() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtautor = new javax.swing.JTextField();
        txttitulo = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        txtpalabrasclave = new javax.swing.JTextField();
        txtedicion = new javax.swing.JTextField();
        txtdisponible = new javax.swing.JTextField();
        txtcopias = new javax.swing.JTextField();
        txtarea = new javax.swing.JTextField();
        txtejemplares = new javax.swing.JTextField();
        txtfrecuencia = new javax.swing.JTextField();
        txttemas = new javax.swing.JTextField();
        combotipo = new javax.swing.JComboBox<>();
        btnvolver = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Modificar Bibliografia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("Tipo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jLabel3.setText("Frecuencia");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        jLabel4.setText("Temas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        Titulo.setText("Titulo");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel6.setText("Descripcion");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel7.setText("Autor");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel8.setText("Edicion");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        jLabel9.setText("Copias");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        jLabel10.setText("Ejemplares");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jLabel11.setText("Disponible");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));

        jLabel12.setText("ARea");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        jLabel13.setText("Palabras Clave");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        txtautor.setColumns(12);
        getContentPane().add(txtautor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        txttitulo.setColumns(12);
        getContentPane().add(txttitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        txtdescripcion.setColumns(12);
        getContentPane().add(txtdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        txtpalabrasclave.setColumns(12);
        getContentPane().add(txtpalabrasclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        txtedicion.setColumns(12);
        getContentPane().add(txtedicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        txtdisponible.setColumns(12);
        getContentPane().add(txtdisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, -1));

        txtcopias.setColumns(12);
        getContentPane().add(txtcopias, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        txtarea.setColumns(12);
        getContentPane().add(txtarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        txtejemplares.setColumns(12);
        getContentPane().add(txtejemplares, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        txtfrecuencia.setColumns(12);
        getContentPane().add(txtfrecuencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        txttemas.setColumns(12);
        txttemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttemasActionPerformed(evt);
            }
        });
        getContentPane().add(txttemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        combotipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libro", "Revista", "Tesis" }));
        getContentPane().add(combotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        btnvolver.setText("Volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1_201602598/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttemasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttemasActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        // TODO add your handling code here:
        
        Usuario_Administrador ua=new Usuario_Administrador();
        ua.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_btnvolverActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        
        int tipo;
        boolean msj=false;
       
        int ind=combotipo.getSelectedIndex();
        
        switch(ind){
            
            case(0):
             
             for(int i=0;i<Bibliografia.longibibliografia;i++){
                 
                 String a=Bibliografia.bibliografia[i];
                 String[] coo=a.split(";");
                 
                 if(txtautor.getText().equals(coo[1])){
                     
                     
                     txttitulo.setText(coo[2]);
                     txtdescripcion.setText(coo[3]);
                     txtpalabrasclave.setText(coo[4]);
                     txtedicion.setText(coo[5]);
                     txttemas.setText(coo[6]);
                     txtcopias.setText(coo[10]);
                     txtdisponible.setText(coo[11]);
                     k=i;
                     msj=true;
                     valor=0;
                     
                 }
                 
        }
             if(msj==false){
            JOptionPane.showMessageDialog(null, "No se ha encontrado este autor en libros",
                    "Aviso",WARNING_MESSAGE);
                
        }
             break;
             
             
           case(1):
               
             for(int i=0;i<Revista.longibibliografia;i++){
                 
                 String a=Revista.bibliografia[i];
                 String[] coo=a.split(";");
                 
                 if(txtautor.getText().equals(coo[1])){
                     
                     
                     txttitulo.setText(coo[2]);
                     txtdescripcion.setText(coo[3]);
                     txtpalabrasclave.setText(coo[4]);
                     txtedicion.setText(coo[5]);
                     txttemas.setText(coo[6]);
                     txtfrecuencia.setText(coo[7]);
                     txtejemplares.setText(coo[8]);
                     txtcopias.setText(coo[10]);
                     txtdisponible.setText(coo[11]);
                     k=i;
                     msj=true;
                     valor=1;
                     
                 }
                 
        }
             if(msj==false){
            JOptionPane.showMessageDialog(null, "No se ha encontrado este autor en Revistas",
                    "Aviso",WARNING_MESSAGE);
                
        }
             break;  
            
            case(2):
                
                
             for(int i=0;i<Tesis.longibibliografia;i++){
                 
                 String a=Tesis.bibliografia[i];
                 String[] coo=a.split(";");
                 
                 if(txtautor.getText().equals(coo[1])){
                     
                     
                     txttitulo.setText(coo[2]);
                     txtdescripcion.setText(coo[3]);
                     txtpalabrasclave.setText(coo[4]);
                     txtedicion.setText(coo[5]);
                     txttemas.setText(coo[6]);
                     txtarea.setText(coo[9]);
                     txtcopias.setText(coo[10]);
                     txtdisponible.setText(coo[11]);
                     k=i;
                     msj=true;
                     valor=2;
                     
                 }
                 
        }
             if(msj==false){
            JOptionPane.showMessageDialog(null, "No se ha encontrado este autor en Revistas",
                    "Aviso",WARNING_MESSAGE);
                
        }
             break; 
                
                
        }//switch
        
        
        
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
       /* Bibliografia b=new Bibliografia();
        Revista r=new Revista();
        Tesis t=new Tesis();*/
       switch(valor){
            
            case(0):
             
                Bibliografia.setBibliografia(k,0,txtautor.getText(), txttitulo.getText(), txtdescripcion.getText(),
                        txtpalabrasclave.getText(),txtedicion.getText(),txttemas.getText(),"","","",
                        txtcopias.getText(), 
                        txtdisponible.getText());
                
                JOptionPane.showMessageDialog(null, "Libro actualizado");
                Limpiar();
                break;
                
                
                
            case(1):
                
                Revista.setRevista(k,1,txtautor.getText(), txttitulo.getText(), txtdescripcion.getText(),
                        txtpalabrasclave.getText(),txtedicion.getText(),txttemas.getText(),
                        txtfrecuencia.getText(),
                        txtejemplares.getText(),"",
                        txtcopias.getText(), 
                        txtdisponible.getText());
                
                JOptionPane.showMessageDialog(null, "Revista Actualizada");
                Limpiar();
                break;
                
            case(2):
            
                Tesis.setTesis(k,2,txtautor.getText(), txttitulo.getText(), txtdescripcion.getText(),
                        txtpalabrasclave.getText(),txtedicion.getText(),txttemas.getText(),
                         
                        "", "",txtarea.getText(),txtcopias.getText(),
                        txtdisponible.getText());
                
                JOptionPane.showMessageDialog(null, "Tesis Actualizada");
                Limpiar();
                break;
            
                
        }
        
        
    }//GEN-LAST:event_btnmodificarActionPerformed

    public void Limpiar(){
        txttitulo.setText(null);
                txtarea.setText(null);
                txtautor.setText(null);
                txtcopias.setText(null);
                txtdescripcion.setText(null);
                txtdisponible.setText(null);
                txtedicion.setText(null);
                txtejemplares.setText(null);
                txtfrecuencia.setText(null);
                        txtpalabrasclave.setText(null);
                 txttemas.setText(null);
                 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar_Bibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar_Bibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar_Bibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_Bibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar_Bibliografia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnvolver;
    private javax.swing.JComboBox<String> combotipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JTextField txtarea;
    private javax.swing.JTextField txtautor;
    private javax.swing.JTextField txtcopias;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtdisponible;
    private javax.swing.JTextField txtedicion;
    private javax.swing.JTextField txtejemplares;
    private javax.swing.JTextField txtfrecuencia;
    private javax.swing.JTextField txtpalabrasclave;
    private javax.swing.JTextField txttemas;
    private javax.swing.JTextField txttitulo;
    // End of variables declaration//GEN-END:variables
}
