/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_201602598;

import javax.swing.JOptionPane;

/**
 *
 * @author Hector
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsalir = new javax.swing.JButton();
        lblusac = new javax.swing.JLabel();
        lbllibro = new javax.swing.JLabel();
        lblinfo = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btnabout = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsalir.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        lblusac.setBackground(new java.awt.Color(255, 255, 255));
        lblusac.setForeground(new java.awt.Color(255, 255, 255));
        lblusac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1_201602598/Imagenes/usac.png"))); // NOI18N
        getContentPane().add(lblusac, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 510, 170));

        lbllibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1_201602598/Imagenes/libros.png"))); // NOI18N
        getContentPane().add(lbllibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 200, 130));

        lblinfo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblinfo.setText("Biblioteca Central - USAC");
        getContentPane().add(lblinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        btnlogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnlogin.setText("Login");
        btnlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));

        btnlogout.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnlogout.setText("Logout");
        getContentPane().add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        btnabout.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnabout.setText("About");
        getContentPane().add(btnabout, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1_201602598/Imagenes/fondo.jpg"))); // NOI18N
        lblfondo.setName(""); // NOI18N
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
         Login log=new Login();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnabout;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblinfo;
    private javax.swing.JLabel lbllibro;
    private javax.swing.JLabel lblusac;
    // End of variables declaration//GEN-END:variables
}
