/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_201602598;

/**
 *
 * @author Hector
 */
public class Usuario_Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Usuario_Administrador
     */
    public Usuario_Administrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblusuarios = new javax.swing.JLabel();
        btncrear = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnver = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();
        btncrear1 = new javax.swing.JButton();
        btnmodificar1 = new javax.swing.JButton();
        btneliminar1 = new javax.swing.JButton();
        btnver1 = new javax.swing.JButton();
        Bibliografica = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblusuarios.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblusuarios.setText("Usuarios");
        getContentPane().add(lblusuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        btncrear.setText("Crear");
        getContentPane().add(btncrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        btnmodificar.setText("Modificar");
        getContentPane().add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        btneliminar.setText("Eliminar");
        getContentPane().add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        btnver.setText("Ver");
        getContentPane().add(btnver, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        btnvolver.setText("Volver");
        getContentPane().add(btnvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        btncrear1.setText("Crear");
        getContentPane().add(btncrear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        btnmodificar1.setText("Modificar");
        getContentPane().add(btnmodificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        btneliminar1.setText("Eliminar");
        getContentPane().add(btneliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        btnver1.setText("Ver");
        getContentPane().add(btnver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        Bibliografica.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Bibliografica.setText("Bibliografia");
        getContentPane().add(Bibliografica, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1_201602598/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario_Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bibliografica;
    private javax.swing.JButton btncrear;
    private javax.swing.JButton btncrear1;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btneliminar1;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnmodificar1;
    private javax.swing.JButton btnver;
    private javax.swing.JButton btnver1;
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblusuarios;
    // End of variables declaration//GEN-END:variables
}
